### PR TITLE
Update dependance

### PR DESCRIPTION
**Pull request by ColonelMoutarde**

### CODE REVIEW

**Comment by ColonelMoutarde** [comment]
Why ?

**Comment by Asxer** [comment]
Because second request depends of it and there is no reasons to divide it to many pull-requests.

**Comment by ColonelMoutarde** [comment]
Strange reason. I have make my PR on GitHub. It’s hard to change many files in on pr. But the it’s same result

**Comment by ColonelMoutarde** [comment]
You can merge twice

**Comment by Asxer** [comment]
@ColonelMoutarde 
>  It’s hard to change many files in on pr

Could you please explain how do you make pull request? Do you pull this code, modify it, check correct working of it, fork and make pull request? Or you doing it in github web-interface without any checking? 

Of course I can merge twice but I will merge only checked code with careful attitude to the development of.

**Pull request closed without merging**
